 
- name: install updates
  apt:
    upgrade: dist
    update_cache: yes

- name: create ansible user
  user:
    name: ansible
    groups: root, sudo

- name: add ssh key for ansible
  authorized_key:
    user: ansible
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF+PANxQ1kgTBetMxOHd50EWqKtLKeOBbfEzPwfFaR+T Ansible"


- name: add sudoers file for simone
  tags: always
  copy:
    src: sudoer_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: add ssh key for admin/root
  authorized_key:
    user: admin
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICiqpOEeCclLUKrfB/gqtdO0ZZ4idG0ucXmCILKE/AL2 matthew@spindler.uk"

- name: add updated sshd_config file to disable password authentication
  tags: always
  copy:
    src: sshd_config
    dest: /etc/ssh
    owner: root
    group: root
    mode: 0440
  notify: restart_sshd
